server:
  port:8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: usuarios
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/usuarios/**

eureka:
  client:
    register-with-eureka: false